version: "3.8"

services:
  python-consumer:
    build: ./python-job-consumer
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - QUEUE_URL=http://localstack:4566/000000000000/order-queue # LocalStack endpoint and queue name
      - PYTHONUNBUFFERED=1
    depends_on:
      localstack:
        condition: service_healthy

  nodejs-app:
    build: ./node-js-enqueue
    ports:
      - "3000:3000"
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - QUEUE_URL=http://localstack:4566/000000000000/order-queue # LocalStack endpoint and queue name
    depends_on:
      localstack:
        condition: service_healthy

  localstack:
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - SERVICES=sqs # Start only the SQS service
      - DEFAULT_REGION=us-east-1
    volumes:
      - "./sqs_bootstrap.sh:/etc/localstack/init/ready.d/init-aws.sh"
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: "curl http://localhost:4566/_localstack/init | grep '\"READY\": true'"
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s
